# Enhanced Yoga Poses Data with full instructions and images

YOGA_POSES_ENHANCED = [
    # EARTH ELEMENT POSES
    {
        "id": "1", 
        "name": "Mountain Pose", 
        "sanskrit_name": "Tadasana", 
        "element": "Earth", 
        "description": "Stand tall like a mountain, rooted and stable. This foundational pose connects you to the earth element and your own inner strength.",
        "image_url": "https://images.unsplash.com/photo-1635366400548-05fefa95193b?w=800",
        "benefits": ["Improves posture and alignment", "Strengthens thighs, knees, and ankles", "Firms abdomen and buttocks", "Relieves sciatica", "Reduces flat feet", "Grounds and centers energy"],
        "chakras": ["Root"],
        "duration_minutes": 3,
        "difficulty": "Beginner",
        "instructions": [
            "Stand with feet together or hip-width apart, toes pointing forward",
            "Spread your toes and press all four corners of your feet into the earth",
            "Engage your thigh muscles, lifting the kneecaps slightly",
            "Tuck your tailbone slightly and engage your core",
            "Roll your shoulders back and down, opening the chest",
            "Let arms hang naturally with palms facing forward",
            "Lengthen through the crown of your head toward the sky",
            "Breathe deeply, feeling rooted yet lifted"
        ],
        "tips": ["Imagine a string pulling you up from the crown of your head", "Close your eyes to improve balance awareness"],
        "contraindications": ["Headache", "Low blood pressure", "Insomnia"],
        "modifications": {"easier": "Stand with back against a wall for support", "advanced": "Close eyes or stand on a folded blanket"}
    },
    {
        "id": "2", 
        "name": "Tree Pose", 
        "sanskrit_name": "Vrksasana", 
        "element": "Earth", 
        "description": "Like a sacred tree, roots deep and branches reaching skyward. Balance between earth and sky.",
        "image_url": "https://images.unsplash.com/photo-1560233026-ad254fa8da38?w=800",
        "benefits": ["Strengthens thighs, calves, ankles, and spine", "Stretches groins, inner thighs, chest, and shoulders", "Improves sense of balance", "Relieves sciatica", "Calms and focuses the mind", "Builds confidence"],
        "chakras": ["Root", "Heart"],
        "duration_minutes": 3,
        "difficulty": "Beginner",
        "instructions": [
            "Begin in Mountain Pose with feet grounded",
            "Shift your weight onto your left foot",
            "Bend your right knee and place the sole of your right foot on your inner left thigh, calf, or ankle (never on the knee)",
            "Press your foot and leg into each other for stability",
            "Find a fixed point (drishti) to gaze at for balance",
            "Bring palms together at heart center, or raise arms overhead like branches",
            "Keep your standing leg strong and your hips level",
            "Hold for 5-10 breaths, then switch sides"
        ],
        "tips": ["Start with foot lower on the leg and work your way up", "Use a wall for support if needed"],
        "contraindications": ["Headache", "Insomnia", "Low blood pressure"],
        "modifications": {"easier": "Keep toes on floor with heel on ankle", "advanced": "Close eyes or add arm variations"}
    },
    {
        "id": "3", 
        "name": "Bridge Pose", 
        "sanskrit_name": "Setu Bandhasana", 
        "element": "Earth", 
        "description": "Create a bridge between earth and sky, opening the heart to receive.",
        "image_url": "https://images.pexels.com/photos/4534574/pexels-photo-4534574.jpeg?w=800",
        "benefits": ["Stretches chest, neck, and spine", "Calms the brain and reduces stress", "Stimulates abdominal organs, lungs, and thyroid", "Rejuvenates tired legs", "Improves digestion", "Reduces anxiety, fatigue, and insomnia"],
        "chakras": ["Heart", "Throat"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "Lie on your back with knees bent, feet flat on the floor hip-width apart",
            "Place arms alongside your body, palms facing down",
            "Walk your feet close enough to touch your heels with your fingertips",
            "Press feet and arms into the floor as you lift your hips toward the ceiling",
            "Roll your shoulders underneath you and clasp hands beneath your pelvis",
            "Keep thighs parallel and knees directly over ankles",
            "Lift your chin slightly away from your chest to protect the neck",
            "Hold for 30 seconds to 1 minute, breathing deeply"
        ],
        "tips": ["Place a block under your sacrum for a supported version", "Keep neck neutral - don't turn your head"],
        "contraindications": ["Neck injury", "Back injury"],
        "modifications": {"easier": "Place a block under sacrum", "advanced": "Lift one leg toward ceiling"}
    },
    {
        "id": "4", 
        "name": "Garland Pose", 
        "sanskrit_name": "Malasana", 
        "element": "Earth", 
        "description": "Deep squat connecting to primal earth energy. Opens the hips and grounds the spirit.",
        "image_url": "https://images.unsplash.com/photo-1593152961455-b943e1cea86b?w=800",
        "benefits": ["Stretches ankles, groins, and back torso", "Tones the belly", "Improves colon function", "Opens hips deeply", "Strengthens metabolism", "Grounds and centers energy"],
        "chakras": ["Root", "Sacral"],
        "duration_minutes": 3,
        "difficulty": "Beginner",
        "instructions": [
            "Stand with feet slightly wider than hip-width apart",
            "Turn your toes out at about 45 degrees",
            "Bend your knees and lower your hips toward the floor into a deep squat",
            "Bring your palms together at heart center in prayer position",
            "Press your elbows against your inner knees to open the hips",
            "Lengthen your spine and lift through the crown of your head",
            "Keep your heels on the ground if possible",
            "Hold for 30 seconds to 1 minute"
        ],
        "tips": ["Place a rolled blanket under heels if they lift", "Sit on a block for support"],
        "contraindications": ["Knee injury", "Lower back injury"],
        "modifications": {"easier": "Sit on a block or place heels on blanket", "advanced": "Wrap arms behind back in a bind"}
    },
    {
        "id": "5", 
        "name": "Extended Triangle", 
        "sanskrit_name": "Utthita Trikonasana", 
        "element": "Earth", 
        "description": "Form the sacred triangle, connecting three points of power between earth and cosmos.",
        "image_url": "https://images.unsplash.com/photo-1561577732-12fffa81b37e?w=800",
        "benefits": ["Stretches legs, hips, groins, hamstrings, calves, shoulders, chest, and spine", "Strengthens thighs, knees, and ankles", "Stimulates abdominal organs", "Reduces stress", "Improves digestion", "Relieves backache"],
        "chakras": ["Root", "Sacral"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "Stand and step feet 3-4 feet apart",
            "Turn right foot out 90 degrees, left foot in slightly",
            "Align right heel with left arch",
            "Raise arms parallel to the floor, palms down",
            "Extend torso to the right, hinging at the hip",
            "Lower right hand to shin, ankle, or floor outside right foot",
            "Extend left arm toward the ceiling",
            "Turn head to gaze at left thumb",
            "Hold for 30 seconds to 1 minute, then switch sides"
        ],
        "tips": ["Use a block under bottom hand if needed", "Keep both sides of torso equally long"],
        "contraindications": ["Diarrhea", "Headache", "Low blood pressure", "Heart condition"],
        "modifications": {"easier": "Use a block under bottom hand", "advanced": "Wrap top arm behind back"}
    },
    {
        "id": "6", 
        "name": "Wide-Legged Forward Fold", 
        "sanskrit_name": "Prasarita Padottanasana", 
        "element": "Earth", 
        "description": "Bow to the earth with legs wide, letting gravity draw you into surrender.",
        "image_url": "https://images.pexels.com/photos/8436686/pexels-photo-8436686.jpeg?w=800",
        "benefits": ["Stretches hamstrings and inner thighs", "Strengthens feet and legs", "Calms the brain", "Relieves mild backache", "Opens hips", "Reduces fatigue"],
        "chakras": ["Root", "Third Eye"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "Stand and step feet 4-5 feet apart",
            "Turn toes slightly inward, heels slightly out",
            "Place hands on hips and lift chest",
            "Exhale and fold forward from the hips",
            "Place hands on the floor beneath shoulders",
            "Lengthen spine on inhale, fold deeper on exhale",
            "Let head hang heavy or place crown on floor",
            "Hold for 30 seconds to 1 minute"
        ],
        "tips": ["Bend knees if hamstrings are tight", "Use blocks under hands for support"],
        "contraindications": ["Lower back issues - keep spine flat"],
        "modifications": {"easier": "Keep hands on blocks or bend knees", "advanced": "Clasp hands behind back"}
    },
    {
        "id": "7", 
        "name": "Chair Pose", 
        "sanskrit_name": "Utkatasana", 
        "element": "Earth", 
        "description": "Sit into an invisible throne, building inner fire while staying rooted.",
        "image_url": "https://images.unsplash.com/photo-1610562269919-86791081ad29?w=800",
        "benefits": ["Strengthens ankles, thighs, calves, and spine", "Stretches shoulders and chest", "Stimulates abdominal organs, diaphragm, and heart", "Reduces flat feet", "Builds heat and stamina"],
        "chakras": ["Root", "Solar Plexus"],
        "duration_minutes": 3,
        "difficulty": "Beginner",
        "instructions": [
            "Stand in Mountain Pose with feet together or hip-width apart",
            "Inhale and raise arms overhead, palms facing each other",
            "Exhale and bend knees as if sitting in a chair",
            "Shift weight into heels - you should be able to lift toes",
            "Keep knees tracking over ankles, not past toes",
            "Draw tailbone down to lengthen lower back",
            "Keep chest lifted and shoulders relaxed",
            "Hold for 30 seconds to 1 minute"
        ],
        "tips": ["Squeeze a block between thighs for alignment", "Keep weight in heels"],
        "contraindications": ["Headache", "Insomnia", "Low blood pressure"],
        "modifications": {"easier": "Don't bend as deep, hands at heart", "advanced": "Rise onto balls of feet"}
    },
    {
        "id": "8", 
        "name": "Standing Forward Fold", 
        "sanskrit_name": "Uttanasana", 
        "element": "Earth", 
        "description": "Fold forward, letting the crown descend toward Mother Earth in humble surrender.",
        "image_url": "https://images.unsplash.com/photo-1554067559-1e017957fa3b?w=800",
        "benefits": ["Calms the brain and helps relieve stress", "Stimulates liver and kidneys", "Stretches hamstrings, calves, and hips", "Strengthens thighs and knees", "Reduces fatigue and anxiety", "Relieves headache and insomnia"],
        "chakras": ["Root", "Crown"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "Stand in Mountain Pose with hands on hips",
            "Exhale and hinge forward from the hips, not the waist",
            "Bend knees as much as needed to bring palms to the floor",
            "Let your head hang heavy, releasing tension in neck",
            "Press heels into floor and lift sit bones toward ceiling",
            "With each inhale, lengthen; with each exhale, release deeper",
            "Hold opposite elbows and sway gently if desired",
            "Hold for 30 seconds to 1 minute"
        ],
        "tips": ["Bend knees generously to protect lower back", "Grab opposite elbows for ragdoll variation"],
        "contraindications": ["Back injury - keep knees bent and spine flat"],
        "modifications": {"easier": "Bend knees deeply, hands on blocks", "advanced": "Grab big toes or wrap hands under feet"}
    },
    {
        "id": "9", 
        "name": "Goddess Pose", 
        "sanskrit_name": "Utkata Konasana", 
        "element": "Earth", 
        "description": "Embody the fierce divine feminine, rooted in power and open in heart.",
        "image_url": "https://images.unsplash.com/photo-1579454563399-9da67b065830?w=800",
        "benefits": ["Strengthens quadriceps, inner thighs, and core", "Opens hips and chest", "Stimulates cardiovascular system", "Builds heat and stamina", "Connects to divine feminine energy"],
        "chakras": ["Root", "Sacral"],
        "duration_minutes": 3,
        "difficulty": "Beginner",
        "instructions": [
            "Stand with feet 3-4 feet apart",
            "Turn toes out to 45 degrees",
            "Bend knees and lower hips to knee height",
            "Keep knees tracking over toes, not caving inward",
            "Tuck tailbone slightly to engage core",
            "Raise arms to shoulder height, bend elbows to 90 degrees",
            "Spread fingers wide like claws, palms facing forward",
            "Hold for 30 seconds to 1 minute"
        ],
        "tips": ["Squeeze glutes to protect knees", "Add pulses for more intensity"],
        "contraindications": ["Knee injury", "Hip injury"],
        "modifications": {"easier": "Don't squat as deep", "advanced": "Rise onto balls of feet"}
    },
    {
        "id": "10", 
        "name": "Half Moon Pose", 
        "sanskrit_name": "Ardha Chandrasana", 
        "element": "Earth", 
        "description": "Balance on one leg like the half moon, grounded yet reaching toward the stars.",
        "image_url": "https://images.unsplash.com/photo-1645148394419-19638fc0b1e2?w=800",
        "benefits": ["Strengthens abdomen, ankles, thighs, buttocks, and spine", "Stretches groins, hamstrings, calves, shoulders, chest, and spine", "Improves coordination and balance", "Relieves stress", "Improves digestion"],
        "chakras": ["Root", "Sacral"],
        "duration_minutes": 3,
        "difficulty": "Intermediate",
        "instructions": [
            "From Triangle Pose on right side, bend right knee",
            "Place right hand on floor about 12 inches in front of right foot",
            "Shift weight into right hand and foot",
            "Lift left leg parallel to floor, flex foot",
            "Stack left hip over right hip",
            "Extend left arm toward ceiling",
            "Turn head to gaze at left hand",
            "Hold for 30 seconds, then switch sides"
        ],
        "tips": ["Use a block under bottom hand", "Practice with back against a wall first"],
        "contraindications": ["Headache", "Low blood pressure", "Diarrhea", "Insomnia"],
        "modifications": {"easier": "Keep bottom hand on block, top hand on hip", "advanced": "Grab top foot in half moon bow"}
    },
    # FIRE ELEMENT POSES
    {
        "id": "11", 
        "name": "Warrior I", 
        "sanskrit_name": "Virabhadrasana I", 
        "element": "Fire", 
        "description": "Embody the warrior spirit with fierce determination and open heart.",
        "image_url": "https://images.unsplash.com/photo-1561577732-12fffa81b37e?w=800",
        "benefits": ["Stretches chest, lungs, shoulders, neck, belly, and groins", "Strengthens shoulders, arms, and back muscles", "Strengthens and stretches thighs, calves, and ankles", "Develops stamina and concentration"],
        "chakras": ["Solar Plexus", "Heart"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "From Mountain Pose, step left foot back 3-4 feet",
            "Turn left foot out 45-60 degrees, right foot forward",
            "Square hips toward front of mat",
            "Bend right knee to 90 degrees, knee over ankle",
            "Keep back leg straight and strong",
            "Inhale and raise arms overhead, palms facing each other",
            "Lift chest and gaze up toward hands",
            "Hold for 30 seconds to 1 minute, then switch sides"
        ],
        "tips": ["Press back heel firmly into floor", "Draw front ribs in to avoid overarching back"],
        "contraindications": ["High blood pressure", "Heart problems"],
        "modifications": {"easier": "Hands on hips or at heart", "advanced": "Deepen the lunge, slight backbend"}
    },
    {
        "id": "12", 
        "name": "Warrior II", 
        "sanskrit_name": "Virabhadrasana II", 
        "element": "Fire", 
        "description": "Stand in your power, gaze fixed on your intention, arms extended in all directions.",
        "image_url": "https://images.unsplash.com/photo-1561577732-12fffa81b37e?w=800",
        "benefits": ["Strengthens and stretches legs and ankles", "Stretches groins, chest, lungs, and shoulders", "Stimulates abdominal organs", "Increases stamina", "Relieves backaches", "Develops concentration and balance"],
        "chakras": ["Solar Plexus", "Sacral"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "Stand and step feet 3-4 feet apart",
            "Turn right foot out 90 degrees, left foot in slightly",
            "Align right heel with left arch",
            "Raise arms parallel to floor, palms down",
            "Bend right knee to 90 degrees over ankle",
            "Keep torso centered, not leaning forward",
            "Turn head to gaze over right fingertips",
            "Hold for 30 seconds to 1 minute, then switch sides"
        ],
        "tips": ["Keep knee tracking over second toe", "Engage core to support lower back"],
        "contraindications": ["Diarrhea", "High blood pressure", "Neck problems - gaze forward instead of over hand"],
        "modifications": {"easier": "Don't bend front knee as deep", "advanced": "Sink deeper, hold longer"}
    },
    {
        "id": "13", 
        "name": "Warrior III", 
        "sanskrit_name": "Virabhadrasana III", 
        "element": "Fire", 
        "description": "Fly like an arrow toward your destiny, balanced and powerful.",
        "image_url": "https://images.unsplash.com/photo-1579454563399-9da67b065830?w=800",
        "benefits": ["Strengthens ankles, legs, shoulders, and back muscles", "Tones the abdomen", "Improves balance and posture", "Calms the mind and improves concentration"],
        "chakras": ["Solar Plexus"],
        "duration_minutes": 3,
        "difficulty": "Intermediate",
        "instructions": [
            "From Warrior I, shift weight into front (right) foot",
            "Hinge forward from hips as you lift back leg",
            "Bring torso and back leg parallel to floor",
            "Reach arms forward alongside ears, or hands at heart",
            "Flex back foot and engage lifted leg strongly",
            "Keep hips level and square to floor",
            "Gaze at floor a few feet ahead",
            "Hold for 30 seconds, then switch sides"
        ],
        "tips": ["Use a wall or chair for balance support", "Focus on one point for stability"],
        "contraindications": ["High blood pressure"],
        "modifications": {"easier": "Hands on blocks, lifted leg lower", "advanced": "Arms back like airplane wings"}
    },
    {
        "id": "14", 
        "name": "Cobra Pose", 
        "sanskrit_name": "Bhujangasana", 
        "element": "Fire", 
        "description": "Rise like the sacred serpent, awakening kundalini energy up the spine.",
        "image_url": "https://images.pexels.com/photos/4534574/pexels-photo-4534574.jpeg?w=800",
        "benefits": ["Strengthens the spine", "Stretches chest, lungs, shoulders, and abdomen", "Firms the buttocks", "Stimulates abdominal organs", "Opens the heart and lungs", "Relieves stress and fatigue"],
        "chakras": ["Heart", "Throat"],
        "duration_minutes": 3,
        "difficulty": "Beginner",
        "instructions": [
            "Lie face down with legs extended, tops of feet on floor",
            "Place hands under shoulders, elbows close to body",
            "Press tops of feet, thighs, and pubic bone into floor",
            "Inhale and begin to straighten arms, lifting chest",
            "Lift only as high as you can while keeping pubic bone on floor",
            "Draw shoulders back and down, away from ears",
            "Keep gaze forward or slightly upward",
            "Hold for 15-30 seconds, breathing easily"
        ],
        "tips": ["Use back muscles, not arm strength, to lift", "Keep elbows slightly bent to protect lower back"],
        "contraindications": ["Back injury", "Carpal tunnel syndrome", "Headache", "Pregnancy"],
        "modifications": {"easier": "Keep elbows on floor (Sphinx Pose)", "advanced": "Straighten arms fully (Upward Dog)"}
    },
    {
        "id": "15", 
        "name": "Upward Facing Dog", 
        "sanskrit_name": "Urdhva Mukha Svanasana", 
        "element": "Fire", 
        "description": "Lift your heart to the sun, chest proud and spine awakened.",
        "image_url": "https://images.pexels.com/photos/4534574/pexels-photo-4534574.jpeg?w=800",
        "benefits": ["Improves posture", "Strengthens spine, arms, and wrists", "Stretches chest, lungs, shoulders, and abdomen", "Firms buttocks", "Stimulates abdominal organs", "Helps relieve depression and fatigue"],
        "chakras": ["Heart", "Throat"],
        "duration_minutes": 3,
        "difficulty": "Intermediate",
        "instructions": [
            "Lie face down with legs extended back, tops of feet on floor",
            "Place hands beside waist, fingers pointing forward",
            "Press into hands and lift torso and legs off floor",
            "Straighten arms fully, keeping shoulders over wrists",
            "Only tops of feet and hands touch the floor",
            "Roll shoulders back, lift chest toward ceiling",
            "Keep thighs firm and engaged, slightly rotated inward",
            "Gaze forward or slightly upward"
        ],
        "tips": ["Press strongly through hands to lift body", "Keep thighs off the floor"],
        "contraindications": ["Back injury", "Carpal tunnel syndrome", "Pregnancy"],
        "modifications": {"easier": "Keep thighs on floor (Cobra)", "advanced": "Hold longer, deeper backbend"}
    },
    {
        "id": "16", 
        "name": "Boat Pose", 
        "sanskrit_name": "Navasana", 
        "element": "Fire", 
        "description": "Balance on your sit bones like a vessel of light, core engaged and spirit strong.",
        "image_url": "https://images.unsplash.com/photo-1663412070733-e7d0031c53f3?w=800",
        "benefits": ["Strengthens abdomen, hip flexors, and spine", "Stimulates kidneys, thyroid, and intestines", "Improves digestion", "Builds core stability", "Relieves stress"],
        "chakras": ["Solar Plexus"],
        "duration_minutes": 3,
        "difficulty": "Intermediate",
        "instructions": [
            "Sit with knees bent, feet flat on floor",
            "Place hands behind thighs, lift chest",
            "Lean back slightly, keeping spine straight",
            "Lift feet off floor, shins parallel to floor",
            "If stable, release hands and extend arms forward",
            "For full pose, straighten legs to 45-degree angle",
            "Keep chest lifted and core engaged",
            "Hold for 10-20 seconds, building up over time"
        ],
        "tips": ["Keep spine long - don't round the back", "Start with bent knees until core is stronger"],
        "contraindications": ["Asthma", "Diarrhea", "Headache", "Heart problems", "Insomnia", "Low blood pressure", "Pregnancy"],
        "modifications": {"easier": "Keep knees bent, hold behind thighs", "advanced": "Lower legs and torso closer to floor"}
    },
    {
        "id": "17", 
        "name": "Plank Pose", 
        "sanskrit_name": "Phalakasana", 
        "element": "Fire", 
        "description": "Hold strong like a sacred plank, building inner fire and resolve.",
        "image_url": "https://images.pexels.com/photos/4534574/pexels-photo-4534574.jpeg?w=800",
        "benefits": ["Strengthens arms, wrists, and spine", "Tones the abdomen", "Builds overall body strength", "Prepares for arm balances", "Develops mental endurance"],
        "chakras": ["Solar Plexus"],
        "duration_minutes": 3,
        "difficulty": "Beginner",
        "instructions": [
            "Start on hands and knees, wrists under shoulders",
            "Step feet back one at a time, coming to balls of feet",
            "Create a straight line from head to heels",
            "Engage core by drawing navel toward spine",
            "Press hands firmly into floor, spreading fingers",
            "Keep neck neutral, gaze slightly ahead of hands",
            "Draw shoulders away from ears",
            "Hold for 30 seconds to 1 minute"
        ],
        "tips": ["Don't let hips sag or pike up", "Engage thighs to take weight off arms"],
        "contraindications": ["Carpal tunnel syndrome"],
        "modifications": {"easier": "Drop knees to floor", "advanced": "Lift one foot off floor"}
    },
    {
        "id": "18", 
        "name": "Side Plank", 
        "sanskrit_name": "Vasisthasana", 
        "element": "Fire", 
        "description": "Balance on one arm, body aligned like a blade of light.",
        "image_url": "https://images.unsplash.com/photo-1645148394419-19638fc0b1e2?w=800",
        "benefits": ["Strengthens arms, belly, and legs", "Stretches and strengthens wrists", "Stretches back of legs", "Improves balance", "Tones obliques"],
        "chakras": ["Solar Plexus", "Heart"],
        "duration_minutes": 3,
        "difficulty": "Intermediate",
        "instructions": [
            "From Plank Pose, shift weight onto right hand",
            "Roll onto outer edge of right foot",
            "Stack left foot on top of right",
            "Lift left arm toward ceiling",
            "Keep body in one straight line",
            "Press firmly through right hand",
            "Lift hips high - don't let them sag",
            "Hold for 15-30 seconds, then switch sides"
        ],
        "tips": ["Stagger feet (one in front of other) for more stability", "Use a wall for support"],
        "contraindications": ["Wrist, elbow, or shoulder injury"],
        "modifications": {"easier": "Lower bottom knee to floor", "advanced": "Lift top leg, grab big toe"}
    },
    {
        "id": "19", 
        "name": "Reverse Warrior", 
        "sanskrit_name": "Viparita Virabhadrasana", 
        "element": "Fire", 
        "description": "Arch back in triumphant glory, heart open to the heavens.",
        "image_url": "https://images.unsplash.com/photo-1561577732-12fffa81b37e?w=800",
        "benefits": ["Stretches side body and intercostal muscles", "Strengthens legs", "Opens hips and chest", "Builds stamina", "Energizes the body"],
        "chakras": ["Solar Plexus", "Heart"],
        "duration_minutes": 3,
        "difficulty": "Beginner",
        "instructions": [
            "From Warrior II, flip front palm to face ceiling",
            "Inhale and reach front arm up and back",
            "Rest back hand lightly on back leg",
            "Keep front knee bent at 90 degrees",
            "Lift through the side body",
            "Gaze up toward raised hand",
            "Keep hips in same alignment as Warrior II",
            "Hold for 30 seconds, then switch sides"
        ],
        "tips": ["Don't collapse into back hand - use core", "Keep front knee stable over ankle"],
        "contraindications": ["Neck injury - gaze forward or down"],
        "modifications": {"easier": "Less backbend, gaze forward", "advanced": "Deeper bend, longer hold"}
    },
    {
        "id": "20", 
        "name": "Crow Pose", 
        "sanskrit_name": "Bakasana", 
        "element": "Fire", 
        "description": "Take flight like the crow messenger, balancing strength and lightness.",
        "image_url": "https://images.unsplash.com/photo-1761579639694-00b779edc398?w=800",
        "benefits": ["Strengthens arms and wrists", "Stretches upper back", "Strengthens abdominal muscles", "Opens groins", "Tones abdominal organs", "Builds confidence and focus"],
        "chakras": ["Solar Plexus", "Root"],
        "duration_minutes": 3,
        "difficulty": "Intermediate",
        "instructions": [
            "Start in a squat with feet together",
            "Place hands on floor shoulder-width apart",
            "Bend elbows and create a shelf with upper arms",
            "Place knees on backs of upper arms, near armpits",
            "Shift weight forward into hands",
            "Lift one foot, then the other, off the floor",
            "Bring feet together behind you",
            "Gaze forward, not down",
            "Hold for 5-10 breaths"
        ],
        "tips": ["Place a cushion in front of you for confidence", "Start by just lifting one foot at a time"],
        "contraindications": ["Carpal tunnel syndrome", "Pregnancy"],
        "modifications": {"easier": "Keep toes on floor, just shift weight", "advanced": "Jump back to Chaturanga from pose"}
    },
    # WATER ELEMENT POSES
    {
        "id": "21", 
        "name": "Child's Pose", 
        "sanskrit_name": "Balasana", 
        "element": "Water", 
        "description": "Return to the womb of the Earth Mother. Surrender and receive comfort.",
        "image_url": "https://images.unsplash.com/photo-1593152961455-b943e1cea86b?w=800",
        "benefits": ["Gently stretches hips, thighs, and ankles", "Calms the brain and relieves stress", "Relieves back and neck pain", "Promotes relaxation", "Helps relieve fatigue"],
        "chakras": ["Third Eye"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "Kneel on floor with big toes touching",
            "Sit on your heels",
            "Separate knees hip-width apart or wider",
            "Exhale and fold torso forward between thighs",
            "Lay torso down on thighs",
            "Extend arms forward with palms down, or rest arms alongside body",
            "Release forehead to the floor",
            "Breathe deeply into back body"
        ],
        "tips": ["Place a blanket under knees for comfort", "Put a pillow under torso for support"],
        "contraindications": ["Diarrhea", "Pregnancy", "Knee injury"],
        "modifications": {"easier": "Place pillow under torso and head", "advanced": "Extend arms back alongside body"}
    },
    {
        "id": "22", 
        "name": "Seated Forward Fold", 
        "sanskrit_name": "Paschimottanasana", 
        "element": "Water", 
        "description": "Bow forward in surrender, releasing into the flow of letting go.",
        "image_url": "https://images.unsplash.com/photo-1593152961455-b943e1cea86b?w=800",
        "benefits": ["Calms the brain and helps relieve stress", "Stretches spine, shoulders, and hamstrings", "Stimulates liver, kidneys, ovaries, and uterus", "Improves digestion", "Soothes headache and anxiety", "Reduces fatigue"],
        "chakras": ["Sacral", "Solar Plexus"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "Sit with legs extended straight in front",
            "Flex feet, press through heels",
            "Inhale and raise arms overhead",
            "Exhale and hinge forward from hips",
            "Reach for feet, ankles, or shins",
            "Keep spine long - don't round excessively",
            "With each inhale, lengthen spine",
            "With each exhale, fold deeper",
            "Hold for 1-3 minutes"
        ],
        "tips": ["Use a strap around feet if needed", "Sit on a blanket to tilt pelvis forward"],
        "contraindications": ["Asthma", "Diarrhea", "Back injury - practice with bent knees"],
        "modifications": {"easier": "Bend knees, use strap", "advanced": "Clasp wrist beyond feet"}
    },
    {
        "id": "23", 
        "name": "Pigeon Pose", 
        "sanskrit_name": "Kapotasana", 
        "element": "Water", 
        "description": "Open the hips where emotions are stored, releasing what no longer serves.",
        "image_url": "https://images.unsplash.com/photo-1663412070733-e7d0031c53f3?w=800",
        "benefits": ["Stretches thighs, groins, and psoas", "Stretches abdomen, chest, shoulders, and neck", "Stimulates abdominal organs", "Opens hips and releases stored emotions"],
        "chakras": ["Sacral", "Root"],
        "duration_minutes": 5,
        "difficulty": "Intermediate",
        "instructions": [
            "From Downward Dog, bring right knee forward behind right wrist",
            "Angle right shin under torso (more parallel for deeper stretch)",
            "Slide left leg back, straighten knee, top of foot on floor",
            "Lower outer right buttock to floor",
            "Keep hips square and level",
            "Walk hands forward, lowering torso over front leg",
            "Rest forehead on hands, block, or floor",
            "Hold for 1-3 minutes, then switch sides"
        ],
        "tips": ["Place a blanket or block under hip for support", "Keep back leg straight and engaged"],
        "contraindications": ["Sacroiliac injury", "Ankle injury", "Knee injury"],
        "modifications": {"easier": "Use block under hip, stay more upright", "advanced": "Reach back and grab back foot (King Pigeon)"}
    },
    {
        "id": "24", 
        "name": "Reclined Bound Angle", 
        "sanskrit_name": "Supta Baddha Konasana", 
        "element": "Water", 
        "description": "Lie back and open like a flower, receiving the flow of life.",
        "image_url": "https://images.unsplash.com/photo-1663412070733-e7d0031c53f3?w=800",
        "benefits": ["Stretches inner thighs, groins, and knees", "Stimulates heart and circulation", "Relieves symptoms of stress and mild depression", "Helps relieve menstrual discomfort"],
        "chakras": ["Sacral", "Heart"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "Lie on your back",
            "Bend knees and bring soles of feet together",
            "Let knees fall open to sides",
            "Place arms alongside body, palms up",
            "Close eyes and relax completely",
            "Allow gravity to open the hips",
            "Breathe deeply into the belly",
            "Hold for 1-5 minutes"
        ],
        "tips": ["Place blocks or blankets under outer thighs for support", "Use a bolster under spine for restorative version"],
        "contraindications": ["Groin or knee injury - support thighs with blocks"],
        "modifications": {"easier": "Support thighs with blocks", "advanced": "Extend arms overhead"}
    },
    {
        "id": "25", 
        "name": "Happy Baby Pose", 
        "sanskrit_name": "Ananda Balasana", 
        "element": "Water", 
        "description": "Return to childlike joy, releasing tension and embracing playfulness.",
        "image_url": "https://images.unsplash.com/photo-1663412070733-e7d0031c53f3?w=800",
        "benefits": ["Gently stretches inner groins and back spine", "Calms the brain", "Helps relieve stress and fatigue", "Opens hips and releases lower back"],
        "chakras": ["Sacral", "Root"],
        "duration_minutes": 3,
        "difficulty": "Beginner",
        "instructions": [
            "Lie on your back",
            "Bend knees into belly",
            "Grip outsides of feet with hands",
            "Open knees wider than torso",
            "Bring knees toward armpits",
            "Stack ankles over knees, shins perpendicular to floor",
            "Flex feet and press up into hands",
            "Gently rock side to side to massage spine"
        ],
        "tips": ["Hold ankles or use a strap if feet are hard to reach", "Keep head and shoulders on floor"],
        "contraindications": ["Pregnancy", "Neck injury - support head with blanket"],
        "modifications": {"easier": "Hold ankles or use strap", "advanced": "Straighten legs toward ceiling"}
    },
    # AIR ELEMENT POSES  
    {
        "id": "26", 
        "name": "Downward Facing Dog", 
        "sanskrit_name": "Adho Mukha Svanasana", 
        "element": "Air", 
        "description": "Create an inverted V, connecting earth and sky. Let gravity release tension.",
        "image_url": "https://images.pexels.com/photos/4534574/pexels-photo-4534574.jpeg?w=800",
        "benefits": ["Calms the brain and helps relieve stress", "Energizes the body", "Stretches shoulders, hamstrings, calves, arches, and hands", "Strengthens arms and legs", "Helps relieve symptoms of menopause", "Improves digestion"],
        "chakras": ["Third Eye", "Crown"],
        "duration_minutes": 5,
        "difficulty": "Beginner",
        "instructions": [
            "Start on hands and knees, wrists under shoulders, knees under hips",
            "Spread fingers wide, press firmly through palms",
            "Tuck toes and lift knees off floor",
            "Lift hips high, straightening legs as much as possible",
            "Press chest toward thighs",
            "Keep arms straight, head between biceps",
            "Press heels toward floor (they don't need to touch)",
            "Hold for 1-3 minutes"
        ],
        "tips": ["Bend knees if hamstrings are tight", "Keep spine long - that's more important than straight legs"],
        "contraindications": ["Carpal tunnel syndrome", "Diarrhea", "Pregnancy (late-term)", "High blood pressure or headache - support head on block"],
        "modifications": {"easier": "Bend knees, walk feet closer to hands", "advanced": "Lift one leg (Three-Legged Dog)"}
    },
    {
        "id": "27", 
        "name": "Eagle Pose", 
        "sanskrit_name": "Garudasana", 
        "element": "Air", 
        "description": "Wrap and squeeze like the sacred eagle, then release and soar.",
        "image_url": "https://images.unsplash.com/photo-1560233026-ad254fa8da38?w=800",
        "benefits": ["Strengthens and stretches ankles and calves", "Stretches thighs, hips, shoulders, and upper back", "Improves concentration and balance", "Improves sense of balance"],
        "chakras": ["Third Eye", "Root"],
        "duration_minutes": 3,
        "difficulty": "Intermediate",
        "instructions": [
            "Stand in Mountain Pose",
            "Bend knees slightly, lift right foot",
            "Cross right thigh over left, hook right foot behind left calf",
            "Extend arms forward, cross left arm over right",
            "Bend elbows, bring palms together (or backs of hands)",
            "Lift elbows to shoulder height, fingers pointing up",
            "Sit deeper into standing leg",
            "Hold for 15-30 seconds, then switch sides"
        ],
        "tips": ["If foot doesn't hook, just cross at thigh", "For arms, just hug shoulders if wrapping is difficult"],
        "contraindications": ["Knee injury"],
        "modifications": {"easier": "Touch toe to floor instead of wrapping", "advanced": "Fold forward in the pose"}
    },
    {
        "id": "28", 
        "name": "Camel Pose", 
        "sanskrit_name": "Ustrasana", 
        "element": "Air", 
        "description": "Arch back into the infinite sky, heart wide open and vulnerable.",
        "image_url": "https://images.unsplash.com/photo-1635617240041-c95219c05542?w=800",
        "benefits": ["Stretches entire front body, ankles, thighs, groins, abdomen, chest, and throat", "Stretches hip flexors (psoas)", "Strengthens back muscles", "Improves posture", "Stimulates abdominal organs"],
        "chakras": ["Heart", "Throat"],
        "duration_minutes": 3,
        "difficulty": "Intermediate",
        "instructions": [
            "Kneel with knees hip-width apart, thighs perpendicular to floor",
            "Place hands on lower back, fingers pointing down",
            "Draw tailbone down, engage core",
            "Inhale and lift chest toward ceiling",
            "Begin to lean back, keeping hips over knees",
            "If available, reach hands to heels one at a time",
            "Let head drop back or keep chin tucked if neck is sensitive",
            "Hold for 30 seconds to 1 minute"
        ],
        "tips": ["Tuck toes under to raise heels if needed", "Keep hips pressing forward over knees"],
        "contraindications": ["High or low blood pressure", "Migraine", "Insomnia", "Serious low back or neck injury"],
        "modifications": {"easier": "Keep hands on lower back", "advanced": "Grab ankles, drop head back fully"}
    },
    # SPIRIT ELEMENT POSES
    {
        "id": "29", 
        "name": "Corpse Pose", 
        "sanskrit_name": "Savasana", 
        "element": "Spirit", 
        "description": "Complete surrender. Die to the old, be reborn in stillness.",
        "image_url": "https://images.unsplash.com/photo-1663412070733-e7d0031c53f3?w=800",
        "benefits": ["Calms the brain and helps relieve stress", "Relaxes the body", "Reduces headache, fatigue, and insomnia", "Helps lower blood pressure", "Integrates practice benefits"],
        "chakras": ["All"],
        "duration_minutes": 10,
        "difficulty": "Beginner",
        "instructions": [
            "Lie on your back with legs extended",
            "Let feet fall open to sides naturally",
            "Place arms alongside body, slightly away, palms up",
            "Close your eyes",
            "Relax every muscle in your body systematically",
            "Release all control of breath and mind",
            "Simply observe without engaging",
            "Remain for 5-15 minutes"
        ],
        "tips": ["Cover with a blanket if cold", "Place bolster under knees if lower back is uncomfortable", "Use eye pillow for deeper relaxation"],
        "contraindications": ["Pregnancy (lie on left side instead)", "Back discomfort - bend knees or use bolster"],
        "modifications": {"easier": "Place bolster under knees", "advanced": "Practice without props, deeper stillness"}
    },
    {
        "id": "30", 
        "name": "Lotus Pose", 
        "sanskrit_name": "Padmasana", 
        "element": "Spirit", 
        "description": "Bloom like the sacred lotus, rooted in mud yet reaching for light.",
        "image_url": "https://images.unsplash.com/photo-1663412070733-e7d0031c53f3?w=800",
        "benefits": ["Opens hips", "Stretches ankles and knees", "Calms the brain", "Increases awareness and attentiveness", "Keeps spine straight", "Traditional meditation posture"],
        "chakras": ["Crown", "Root"],
        "duration_minutes": 10,
        "difficulty": "Advanced",
        "instructions": [
            "Sit on floor with legs extended",
            "Bend right knee and cradle leg, externally rotating hip",
            "Place right foot on top of left thigh, sole facing up",
            "Bend left knee and place left foot on right thigh",
            "Pull heels close to abdomen",
            "Keep spine erect, crown lifting",
            "Place hands on knees in preferred mudra",
            "Close eyes and breathe naturally"
        ],
        "tips": ["Take years to develop this pose safely", "Never force the knees", "Half Lotus is a good preparation"],
        "contraindications": ["Ankle injury", "Knee injury"],
        "modifications": {"easier": "Half Lotus or Easy Pose", "advanced": "Add arm balances or binds"}
    }
]
