import { Hexagon, Square, Star, Globe, Zap } from "lucide-react";

export const categories = [
  {
    id: "sacred_geometry",
    name: "Sacred Geometry",
    icon: Hexagon,
    color: "text-violet-300",
    bg: "bg-violet-500/10",
    border: "border-violet-500/20",
    description: "The mathematical patterns underlying all creation",
    philosophy: "These patterns teach that spirit is not separate from matter. Form itself can become a doorway into reverence, coherence, and direct contact with the intelligence of life.",
    lineage: "Egyptian temple science, Pythagorean schools, yantra traditions, and contemplative geometry",
    integration: "Best for restoring order when the mind feels scattered or spiritually overextended.",
  },
  {
    id: "ancient_alphabets",
    name: "Ancient Alphabets",
    icon: Square,
    color: "text-amber-300",
    bg: "bg-amber-500/10",
    border: "border-amber-500/20",
    description: "Sacred symbols from ancient wisdom traditions",
    philosophy: "Sacred letters were once understood as powers — breaths, names, and vibrational keys. They shape the inner world before they ever become spoken language.",
    lineage: "Sanskrit mantra, Hebrew mysticism, hieroglyphic priesthoods, Ogham, Adinkra, and calligraphic traditions",
    integration: "Best for sound work, mantra, prayer, and remembering the body as a resonant instrument.",
  },
  {
    id: "light_language_symbols",
    name: "Light Language",
    icon: Star,
    color: "text-cyan-300",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/20",
    description: "Activational codes for spiritual awakening",
    philosophy: "These symbols work more through felt resonance than literal definition. They give the intuitive mind permission to speak in image, pulse, sensation, and subtle memory.",
    lineage: "Visionary healing arts, kundalini symbolism, sigil work, ecstatic devotion, and modern energy transmission",
    integration: "Best for inner activation work — but always grounded back into breath, body, and daily life.",
  },
  {
    id: "galactic_codes",
    name: "Galactic Codes",
    icon: Globe,
    color: "text-indigo-300",
    bg: "bg-indigo-500/10",
    border: "border-indigo-500/20",
    description: "Light transmissions from star systems & galactic civilizations",
    philosophy: "Star teachings become medicine when they expand identity without disconnecting us from Earth. They help the soul remember scale, perspective, and cosmic participation.",
    lineage: "Star lore, temple astronomy, navigational cosmologies, and contemporary galactic remembrance streams",
    integration: "Best when you need hope, perspective, and a wider frame for your life path.",
  },
  {
    id: "chakra_codes",
    name: "Chakra Activation",
    icon: Zap,
    color: "text-rose-300",
    bg: "bg-rose-500/10",
    border: "border-rose-500/20",
    description: "Sacred codes for each energy center from Earth Star to Stellar Gateway",
    philosophy: "The chakra map is profound because it refuses to split consciousness from the body. Every center is a spiritual lesson lived through sensation, emotion, voice, action, and awareness.",
    lineage: "Tantric subtle-body science, mantra yoga, integrative energy work, and embodied mysticism",
    integration: "Best for full-spectrum healing where grounding, emotion, voice, intuition, and spirit all need to come into relationship.",
  },
];

export const modalTabs = [
  { id: "essence", label: "Essence" },
  { id: "why", label: "Why It Heals" },
  { id: "traditions", label: "Ancient Traditions" },
  { id: "practice", label: "Practice Guide" },
];