import { Hexagon, Square, Star, Globe, Zap, Orbit } from "lucide-react";

export const categories = [
  {
    id: "encoded_frequency",
    name: "Encoded Frequency",
    icon: Orbit,
    color: "text-yellow-200",
    bg: "bg-yellow-500/10",
    border: "border-yellow-500/30",
    description: "Contemporary visionary sigils and ceremonial contemplation seals",
    philosophy: "Encoded Frequency is a contemporary symbolic practice: luminous forms can be used as prayer-geometry for breath, imagination, reflection, and embodied remembrance. No measurable frequency or transmission is implied.",
    lineage: "Sigil arts, visionary art, sacred-geometry mysticism, and contemporary light-code ceremony",
    integration: "Use for reflective ritual, creative contemplation, and moments when you want to gather attention around one symbol or intention.",
  },
  {
    id: "sacred_geometry",
    name: "Sacred Geometry",
    icon: Hexagon,
    color: "text-violet-300",
    bg: "bg-violet-500/10",
    border: "border-violet-500/20",
    description: "Geometric forms explored through mathematics, art, architecture & contemplative traditions",
    philosophy: "Sacred geometry can be approached as embodied philosophy: pattern, proportion and symmetry become anchors for attention, breath, posture and reflection. The spiritual meanings offered here are contemplative interpretations rather than medical effects of the shapes themselves.",
    lineage: "Egyptian temple science, Pythagorean and Platonic schools, Vedic yantra traditions, Islamic geometric arts, and contemplative architecture lineages",
    integration: "Use geometry when mind, emotion, and life direction feel diffuse. Work one form for seven days with paced breath, body tracking, and one daily integration action so stability is built, not imagined.",
  },
  {
    id: "ancient_alphabets",
    name: "Ancient Alphabets",
    icon: Square,
    color: "text-amber-300",
    bg: "bg-amber-500/10",
    border: "border-amber-500/20",
    description: "Sacred symbols from ancient wisdom traditions",
    philosophy: "Sacred scripts and symbol systems have carried religious, philosophical, artistic and ritual meaning in their own cultures. Here they are approached with context and respect, using careful looking, pronunciation where appropriate, breath and reflection rather than treating all scripts as one universal technology.",
    lineage: "Sanskrit mantra science, Hebrew mysticism, Egyptian hieratic lineages, Ogham streams, Adinkra philosophy, and sacred calligraphic schools",
    integration: "Best for mantra, prayer, speech repair, and relational coherence work. Pair symbol contemplation with vocal tone, paced breathing, and a concrete communication action.",
  },
  {
    id: "light_language_symbols",
    name: "Light Language",
    icon: Star,
    color: "text-cyan-300",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/20",
    description: "Contemporary visionary symbols for contemplative spiritual practice",
    philosophy: "Light language is presented here as a contemporary visionary and devotional practice. Image, sound, sensation and imagination may carry personal meaning without requiring a literal transmission or predetermined activation. Grounding and discernment remain part of every practice.",
    lineage: "Visionary healing arts, kundalini symbolism, sigil craft, ecstatic devotional pathways, and contemporary energy-transmission streams",
    integration: "Use for intuitive exploration, creative prayer and symbolic reflection. Close with grounding and one practical integration action.",
  },
  {
    id: "galactic_codes",
    name: "Galactic Codes",
    icon: Globe,
    color: "text-indigo-300",
    bg: "bg-indigo-500/10",
    border: "border-indigo-500/20",
    description: "Star-inspired symbols, sky lore & contemporary galactic spirituality",
    philosophy: "Galactic Codes brings together real sky observation, historical star lore and contemporary starseed/galactic spirituality. Claims about star beings or civilizations are treated as metaphysical or imaginal teachings, not established astronomy or human ancestry.",
    lineage: "Astronomy and star lore, navigational cosmologies, mythic sky traditions, and contemporary galactic/starseed spirituality",
    integration: "Use for awe, perspective and symbolic contemplation. Pair sky practice with Earth contact and an ordinary-life integration action.",
  },
  {
    id: "chakra_codes",
    name: "Chakra Activation",
    icon: Zap,
    color: "text-rose-300",
    bg: "bg-rose-500/10",
    border: "border-rose-500/20",
    description: "Contemplative symbols for chakra and extended subtle-body maps",
    philosophy: "Chakras are explored here as subtle-body and contemplative maps. Traditional chakra systems vary, while Earth Star, Soul Star and Stellar Gateway belong largely to later esoteric systems. Practices use sensation, breath, imagery and reflection without treating chakras as anatomical organs.",
    lineage: "Tantric subtle-body science, mantra yoga, integrative energy medicine, somatic mysticism, and contemporary nervous-system-informed practice",
    integration: "Work with one center as a reflective theme, then integrate through body awareness, speech and action.",
  },
];

export const modalTabs = [
  { id: "essence", label: "Essence" },
  { id: "why", label: "How It May Support" },
  { id: "traditions", label: "Ancient Traditions" },
  { id: "ceremony", label: "Ceremony & Symbols" },
  { id: "practice", label: "Practice Guide" },
];