import { Hexagon, Square, Star, Globe, Zap, Orbit } from "lucide-react";

export const categories = [
  {
    id: "encoded_frequency",
    name: "Encoded Frequency",
    icon: Orbit,
    color: "text-yellow-200",
    bg: "bg-yellow-500/10",
    border: "border-yellow-500/30",
    description: "High-order transmission sigils and ceremonial frequency seals",
    philosophy: "Encoded frequencies act like living prayer-geometry: they bridge symbol, breath, and embodied remembrance through luminous pattern fields.",
    lineage: "Temple sigil arts, visionary transmission streams, sacred geometry mysticism, and modern light-code ceremony",
    integration: "Best for initiation windows, deep ritual nights, and coherence resets when your field feels fragmented.",
  },
  {
    id: "sacred_geometry",
    name: "Sacred Geometry",
    icon: Hexagon,
    color: "text-violet-300",
    bg: "bg-violet-500/10",
    border: "border-violet-500/20",
    description: "The mathematical patterns underlying all creation",
    philosophy: "Sacred geometry is not visual decoration — it is structural medicine. These forms retrain perception toward order, proportion, and coherence so the nervous system can shift from fragmentation into trust. In this temple, geometry is practiced as embodied philosophy: breath, posture, attention, and ethical action aligned around one form until insight becomes lived behavior.",
    lineage: "Egyptian temple science, Pythagorean and Platonic schools, Vedic yantra traditions, Islamic geometric arts, and contemplative architecture lineages",
    integration: "Use geometry when mind, emotion, and life direction feel diffuse. Work one form for seven days with paced breath, body tracking, and one daily integration action so stability is built, not imagined.",
  },
  {
    id: "ancient_alphabets",
    name: "Ancient Alphabets",
    icon: Square,
    color: "text-amber-300",
    bg: "bg-amber-500/10",
    border: "border-amber-500/20",
    description: "Sacred symbols from ancient wisdom traditions",
    philosophy: "Ancient alphabets were practiced as vibrational technologies. Every stroke, phoneme, and cadence carried instruction for consciousness, memory, and ethical orientation. Their value here is not historical novelty but living embodiment — using sacred language to regulate breath, refine speech, and cultivate integrity in relationship.",
    lineage: "Sanskrit mantra science, Hebrew mysticism, Egyptian hieratic lineages, Ogham streams, Adinkra philosophy, and sacred calligraphic schools",
    integration: "Best for mantra, prayer, speech repair, and relational coherence work. Pair symbol contemplation with vocal tone, paced breathing, and a concrete communication action.",
  },
  {
    id: "light_language_symbols",
    name: "Light Language",
    icon: Star,
    color: "text-cyan-300",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/20",
    description: "Activational codes for spiritual awakening",
    philosophy: "Light language is a felt-spectrum transmission practice: image, pulse, sensation, and emotional movement operating before linear explanation. In this app, it is grounded through ritual pacing so activation does not become spiritual overwhelm. The aim is coherent awakening — expanded perception with embodied safety.",
    lineage: "Visionary healing arts, kundalini symbolism, sigil craft, ecstatic devotional pathways, and contemporary energy-transmission streams",
    integration: "Best for inner activation, emotional release, and intuitive restoration. Always close with grounding, hydration, and one practical behavior change.",
  },
  {
    id: "galactic_codes",
    name: "Galactic Codes",
    icon: Globe,
    color: "text-indigo-300",
    bg: "bg-indigo-500/10",
    border: "border-indigo-500/20",
    description: "Light transmissions from star systems & galactic civilizations",
    philosophy: "Galactic codes are perspective medicine: they widen identity, reduce despair loops, and restore existential orientation. Their function is not escapism but scale calibration — remembering that earthly challenge can be held inside a larger intelligent cosmos while staying accountable to daily life.",
    lineage: "Temple astronomy, star-lore initiations, navigational cosmologies, and contemporary galactic remembrance lineages",
    integration: "Best for meaning crises, direction resets, and hope restoration. Pair star contemplation with earth-contact and immediate service action.",
  },
  {
    id: "chakra_codes",
    name: "Chakra Activation",
    icon: Zap,
    color: "text-rose-300",
    bg: "bg-rose-500/10",
    border: "border-rose-500/20",
    description: "Sacred codes for each energy center from Earth Star to Stellar Gateway",
    philosophy: "Chakra activation is embodied systems work. Each center represents a developmental and relational task — safety, emotion, agency, love, voice, intuition, and spiritual trust — practiced through sensation and behavior, not concept alone.",
    lineage: "Tantric subtle-body science, mantra yoga, integrative energy medicine, somatic mysticism, and contemporary nervous-system-informed practice",
    integration: "Best for full-spectrum healing when different layers of self are out of relationship. Work one center intentionally, then integrate through body, speech, and action.",
  },
];

export const modalTabs = [
  { id: "essence", label: "Essence" },
  { id: "why", label: "Why It Heals" },
  { id: "traditions", label: "Ancient Traditions" },
  { id: "ceremony", label: "Ceremony & Symbols" },
  { id: "practice", label: "Practice Guide" },
];